#pragma once

enum GS_TYPE {
	GS_WELCOME = 1,
	GS_MAINMENU = 2,
	GS_OPTIONMENU = 3,
	GS_CREDIT = 4,
	GS_PETMENU = 5,
	GS_CHARACTERMENU = 6,
	GS_GAMEPLAY = 7,
	GS_GAMEPAUSE = 8,
	GS_GAMEEND = 9,
	GS_BACK = 15,
	GS_NULL = 16,
	GS_EXIT = 17,
	GS_HIGHSCORE = 18
};